version: '3.5'
services:
  gateway:
    image: nginx:1.11
    ports:
      - 88:80
      - 443:443
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro
    depends_on:
      - ms_user
    networks:
      - ms_network
  ms_mongo:
    image: mongo
    container_name: ms_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/configdb
      - mongo_data:/data/mysql
    ports:
      - 27017:27017
    networks:
      - ms_network
  ms_gatekeeper:
    container_name: ms_gatekeeper
    build: ./gatekeeper/
    image: ms_gatekeeper
    volumes:
      - ./gatekeeper/:/usr/src/app
      - gatekeeper_modules:/usr/src/app/node_modules
    ports:
      - 4001:3000
    depends_on:
      - ms_mongo
      - ms_redis
    networks:
      - ms_network
  ms_user:
    build: ./user-service/
    image: user-service
    container_name: ms_user
    environment:
      - NODE_ENV=local
    volumes:
      - ./user-service/:/usr/src/app
      - user_modules:/usr/src/app/node_modules
    ports:
      - 4004:3000
      - 8202:8202
    depends_on:
      - ms_mongo
    networks:
      - ms_network
  ms_redis:
    container_name: ms_redis
    image: redis:4.0
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - ms_network
networks:
  ms_network:
    driver: bridge
    name: ms_network
volumes:
  mongo_data:
    name: global_mongo
  gatekeeper_modules:
    name: global_gatekeeper
  redis_data:
    name: global_redis
  user_modules:
    name: global_user
